/*
 * Hexabot — Fair Core License (FCL-1.0-ALv2)
 * Copyright (c) 2025 Hexastack.
 * Full terms: see LICENSE.md.
 */

import { SettingCreateDto } from '../dto/setting.dto';
import { SettingType } from '../types';

export const DEFAULT_SETTINGS = [
  {
    group: 'chatbot_settings',
    label: 'default_nlu_helper',
    value: 'llm-nlu-helper',
    type: SettingType.select,
    config: {
      multiple: false,
      allowCreate: false,
      entity: 'Helper',
      idKey: 'name',
      labelKey: 'name',
    },
    weight: 1,
  },
  {
    group: 'chatbot_settings',
    label: 'default_nlu_penalty_factor',
    value: 0.95,
    type: SettingType.number,
    config: {
      min: 0,
      max: 1,
      step: 0.01,
    },
    weight: 2,
  },
  {
    group: 'chatbot_settings',
    label: 'default_llm_helper',
    value: 'ollama-helper',
    type: SettingType.select,
    config: {
      multiple: false,
      allowCreate: false,
      entity: 'Helper',
      idKey: 'name',
      labelKey: 'name',
    },
    weight: 3,
  },
  {
    group: 'chatbot_settings',
    label: 'default_flow_escape_helper',
    value: '',
    type: SettingType.select,
    config: {
      multiple: false,
      allowCreate: false,
      entity: 'Helper',
      idKey: 'name',
      labelKey: 'name',
    },
    weight: 3,
  },
  {
    group: 'chatbot_settings',
    label: 'default_storage_helper',
    value: 'local-storage-helper',
    type: SettingType.select,
    config: {
      multiple: false,
      allowCreate: false,
      entity: 'Helper',
      idKey: 'name',
      labelKey: 'name',
    },
    weight: 4,
  },
  {
    group: 'chatbot_settings',
    label: 'global_fallback',
    value: true,
    type: SettingType.checkbox,
    weight: 5,
  },
  {
    group: 'chatbot_settings',
    label: 'fallback_message',
    value: [
      "Sorry but i didn't understand your request. Maybe you can check the menu",
      "I'm really sorry but i don't quite understand what you are saying :(",
    ] as string[],
    type: SettingType.multiple_text,
    weight: 6,
    translatable: true,
  },
  {
    group: 'rag_settings',
    label: 'enabled',
    value: false,
    type: SettingType.checkbox,
    weight: 1,
  },
  {
    group: 'rag_settings',
    label: 'default_mode',
    value: 'lexical',
    type: SettingType.select,
    options: ['embedding', 'lexical'],
    weight: 2,
  },
  {
    group: 'rag_settings',
    label: 'embedding_provider',
    value: 'openai',
    type: SettingType.text,
    weight: 3,
  },
  {
    group: 'rag_settings',
    label: 'embedding_model',
    value: 'text-embedding-3-small',
    type: SettingType.text,
    weight: 4,
  },
  {
    group: 'rag_settings',
    label: 'embedding_api_key',
    value: '',
    type: SettingType.secret,
    weight: 5,
  },
  {
    group: 'rag_settings',
    label: 'embedding_base_url',
    value: '',
    type: SettingType.text,
    weight: 6,
  },
  {
    group: 'rag_settings',
    label: 'embedding_dimensions',
    value: 1536,
    type: SettingType.number,
    config: {
      min: 1,
      max: 4096,
      step: 1,
    },
    weight: 7,
  },
  {
    group: 'rag_settings',
    label: 'top_k',
    value: 3,
    type: SettingType.number,
    config: {
      min: 1,
      max: 50,
      step: 1,
    },
    weight: 8,
  },
  {
    group: 'rag_settings',
    label: 'index_only_active_content',
    value: true,
    type: SettingType.checkbox,
    weight: 9,
  },
  {
    group: 'contact',
    label: 'contact_email_recipient',
    value: 'admin@example.com',
    type: SettingType.text,
    weight: 1,
  },
  {
    group: 'contact',
    label: 'company_name',
    value: 'Your company name',
    type: SettingType.text,
    weight: 2,
  },
  {
    group: 'contact',
    label: 'company_phone',
    value: '(+999) 9999 9999 999',
    type: SettingType.text,
    weight: 3,
  },
  {
    group: 'contact',
    label: 'company_email',
    value: 'contact[at]mycompany.com',
    type: SettingType.text,
    weight: 4,
  },
  {
    group: 'contact',
    label: 'company_address1',
    value: '71 Pilgrim Avenue',
    type: SettingType.text,
    weight: 5,
  },
  {
    group: 'contact',
    label: 'company_address2',
    value: '',
    type: SettingType.text,
    weight: 6,
  },
  {
    group: 'contact',
    label: 'company_city',
    value: 'Chevy Chase',
    type: SettingType.text,
    weight: 7,
  },
  {
    group: 'contact',
    label: 'company_zipcode',
    value: '85705',
    type: SettingType.text,
    weight: 8,
  },
  {
    group: 'contact',
    label: 'company_state',
    value: 'Orlando',
    type: SettingType.text,
    weight: 9,
  },
  {
    group: 'contact',
    label: 'company_country',
    value: 'US',
    type: SettingType.text,
    weight: 10,
  },
] as const satisfies SettingCreateDto[];
