version: '3.8'

services:
  ludwig-visualization:
    image: ludwigai/ludwig:master
    command: >
      visualize --visualization learning_curves
      --ground_truth_metadata /results/experiment_run_0/model/training_set_metadata.json
      --training_statistics /results/experiment_run_0/training_statistics.json
      --file_format png
      --output_directory /visualizations
    volumes:
      - ./visualizations:/visualizations
    environment:
      - PYTHONUNBUFFERED=1  # Optional, to ensure logs are printed immediately
    networks:
      - default

networks:
  default:
    driver: bridge