version: '3.8'

services:
  ludwig-predict:
    image: ludwigai/ludwig:master
    command: >
      predict
      --model_path /src/results/experiment_run/model
      --dataset /data/predict.csv
      --output_directory /src/predictions
    volumes:
      - ./data:/data
      - ./src:/src