version: '3.8'

services:
  ludwig-visualization:
    image: ludwigai/ludwig:master
    command: >
      visualize --visualization learning_curves
      --ground_truth_metadata /src/results/experiment_run_0/model/training_set_metadata.json
      --training_statistics /src/results/experiment_run_0/training_statistics.json
      --file_format png
      --output_directory /src/results/visualizations
    volumes:
      - ./src:/src
    environment:
      - PYTHONUNBUFFERED=1  # Optional, to ensure logs are printed immediately
    working_dir: /src/results
    networks:
      - default

networks:
  default:
    driver: bridge